apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  clusterIP: None # this makes the service headless
  selector:
    component: mysql
    project: roboshop
    tier: database  # has to match with statefulset labels
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port