apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  clusterIP: None # this makes the service headless
  selector:
    component: redis
    project: roboshop
    tier: database  # has to match with statefulset labels
  ports:
  - protocol: TCP
    port: 6379 # service port
    targetPort: 6379 # container port