apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: catalogue
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        component: catalogue
        project: roboshop
        tier: app
    spec:
      containers:
      - name: catalogue
        image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion }}"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        envFrom:
        - configMapRef:
            name: catalogue